export const CONFIG = {
  // Frequency tolerance as percentage (e.g., 0.05 = 5%)
  FREQUENCY_TOLERANCE_PERCENT: 0.08,
  // Minimum amplitude threshold (0-255)
  MIN_AMPLITUDE_THRESHOLD: 30,
  // Tone duration in milliseconds
  TONE_DURATION_MS: 200,
  // Gap between tones in milliseconds
  TONE_GAP_MS: 50,
};

export const SCHEMA_CONFIGS = {
  basic: {
    name: 'Basic',
    schemaPath: '../schema/basic.json',
    icon: '📻',
    range: '3000-8000 Hz',
    description: 'Logarithmic spacing',
    FREQUENCY_TOLERANCE_PERCENT: 0.08,
    MIN_AMPLITUDE_THRESHOLD: 30,
    TONE_DURATION_MS: 200,
    TONE_GAP_MS: 50,
    fftSize: 8192,
    minFreq: 2900,
    maxFreq: 8100,
  },
  voice: {
    name: 'Voice-Optimized',
    schemaPath: '../schema/voice.json',
    icon: '🎤',
    range: '300-3500 Hz',
    description: 'Speech-optimized',
    FREQUENCY_TOLERANCE_PERCENT: 0.08,
    MIN_AMPLITUDE_THRESHOLD: 30,
    TONE_DURATION_MS: 200,
    TONE_GAP_MS: 50,
    fftSize: 16384,
    minFreq: 250,
    maxFreq: 3600,
  },
  ultrasonic: {
    name: 'Ultrasonic',
    schemaPath: '../schema/ultrasonic.json',
    icon: '🚀',
    range: '8000-17000 Hz',
    description: 'No voice interference',
    FREQUENCY_TOLERANCE_PERCENT: 0.08,
    MIN_AMPLITUDE_THRESHOLD: 30,
    TONE_DURATION_MS: 200,
    TONE_GAP_MS: 50,
    fftSize: 8192,
    minFreq: 7500,
    maxFreq: 17500,
  },
  single: {
    name: 'Single-Tone',
    schemaPath: '../schema/single.json',
    icon: '⚡',
    range: '2000-6000 Hz',
    description: '2x faster - 1 tone per char',
    FREQUENCY_TOLERANCE_PERCENT: 0.08,
    MIN_AMPLITUDE_THRESHOLD: 30,
    TONE_DURATION_MS: 120,
    TONE_GAP_MS: 30,
    fftSize: 8192,
    minFreq: 1900,
    maxFreq: 6100,
  },
  quad: {
    name: 'Quad-Tone',
    schemaPath: '../schema/quad.json',
    icon: '🎯',
    range: '1000-5000 Hz',
    description: '4 tones per char - max density',
    FREQUENCY_TOLERANCE_PERCENT: 0.08,
    MIN_AMPLITUDE_THRESHOLD: 30,
    TONE_DURATION_MS: 250,
    TONE_GAP_MS: 50,
    fftSize: 16384,  // Higher FFT for better low-frequency resolution
    minFreq: 900,
    maxFreq: 5100,
  },
};
